export type IPopularCity = {
	rank: number;
	city: string;
	country: string;
};

export type ICitiesList = {
	Key: string;
	LocalizedName: string;
	EnglishName: string;
};

export const PopularCities: IPopularCity[] = [
	{ rank: 1, city: "Bangkok", country: "Thailand" },
	{ rank: 2, city: "Paris", country: "France" },
	{ rank: 3, city: "London", country: "United Kingdom" },
	{ rank: 4, city: "Dubai", country: "United Arab Emirates" },
	{ rank: 5, city: "Singapore", country: "Singapore" },
	{ rank: 6, city: "New York City", country: "USA" },
	{ rank: 7, city: "Kuala Lumpur", country: "Malaysia" },
	{ rank: 8, city: "Istanbul", country: "Turkey" },
	{ rank: 9, city: "Tokyo", country: "Japan" },
	{ rank: 10, city: "Seoul", country: "South Korea" },
	{ rank: 11, city: "Antalya", country: "Turkey" },
	{ rank: 12, city: "Phuket", country: "Thailand" },
	{ rank: 13, city: "Mecca", country: "Saudi Arabia" },
	{ rank: 14, city: "Hong Kong", country: "Hong Kong" },
	{ rank: 15, city: "Milan", country: "Italy" },
	{ rank: 16, city: "Palma de Mallorca", country: "Spain" },
	{ rank: 17, city: "Barcelona", country: "Spain" },
	{ rank: 18, city: "Pattaya", country: "Thailand" },
	{ rank: 19, city: "Osaka", country: "Japan" },
	{ rank: 20, city: "Bali", country: "Indonesia" },
	{ rank: 21, city: "Los Angeles", country: "USA" },
	{ rank: 22, city: "Las Vegas", country: "USA" },
	{ rank: 23, city: "Vienna", country: "Austria" },
	{ rank: 24, city: "Amsterdam", country: "Netherlands" },
	{ rank: 25, city: "Prague", country: "Czech Republic" },
	{ rank: 26, city: "Miami", country: "USA" },
	{ rank: 27, city: "Hong Kong", country: "China" },
	{ rank: 28, city: "Taipei", country: "Taiwan" },
	{ rank: 29, city: "Rome", country: "Italy" },
	{ rank: 30, city: "Mumbai", country: "India" },
	{ rank: 31, city: "Chennai", country: "India" },
	{ rank: 32, city: "Agra", country: "India" },
	{ rank: 33, city: "Delhi", country: "India" },
	{ rank: 34, city: "Johannesburg", country: "South Africa" },
	{ rank: 35, city: "Mumbai", country: "India" },
	{ rank: 36, city: "Berlin", country: "Germany" },
	{ rank: 37, city: "Sydney", country: "Australia" },
	{ rank: 38, city: "Bangkok", country: "Thailand" },
	{ rank: 39, city: "Madrid", country: "Spain" },
	{ rank: 40, city: "Doha", country: "Qatar" },
	{ rank: 41, city: "Ho Chi Minh City", country: "Vietnam" },
	{ rank: 42, city: "San Francisco", country: "USA" },
	{ rank: 43, city: "Guangzhou", country: "China" },
	{ rank: 44, city: "Osaka", country: "Japan" },
	{ rank: 45, city: "Shanghai", country: "China" },
	{ rank: 46, city: "Riyadh", country: "Saudi Arabia" },
	{ rank: 47, city: "Mumbai", country: "India" },
	{ rank: 48, city: "Barcelona", country: "Spain" },
	{ rank: 49, city: "Kolkata", country: "India" },
	{ rank: 50, city: "Hong Kong", country: "China" },
	{ rank: 51, city: "Jaipur", country: "India" },
	{ rank: 52, city: "New Delhi", country: "India" },
	{ rank: 53, city: "Cairo", country: "Egypt" },
	{ rank: 54, city: "Mexico City", country: "Mexico" },
	{ rank: 55, city: "Shanghai", country: "China" },
	{ rank: 56, city: "Los Angeles", country: "USA" },
	{ rank: 57, city: "Shenzhen", country: "China" },
	{ rank: 58, city: "Orlando", country: "USA" },
	{ rank: 59, city: "Rio de Janeiro", country: "Brazil" },
	{ rank: 60, city: "Cape Town", country: "South Africa" },
	{ rank: 61, city: "Venice", country: "Italy" },
	{ rank: 62, city: "Bucharest", country: "Romania" },
	{ rank: 63, city: "Rio de Janeiro", country: "Brazil" },
	{ rank: 64, city: "Moscow", country: "Russia" },
	{ rank: 65, city: "Beijing", country: "China" },
	{ rank: 66, city: "Rome", country: "Italy" },
	{ rank: 67, city: "Vienna", country: "Austria" },
	{ rank: 68, city: "Cancun", country: "Mexico" },
	{ rank: 69, city: "Hanoi", country: "Vietnam" },
	{ rank: 70, city: "Florence", country: "Italy" },
	{ rank: 71, city: "Vienna", country: "Austria" },
	{ rank: 72, city: "Budapest", country: "Hungary" },
	{ rank: 73, city: "Lima", country: "Peru" },
	{ rank: 74, city: "Munich", country: "Germany" },
	{ rank: 75, city: "Lisbon", country: "Portugal" },
	{ rank: 76, city: "Seoul", country: "South Korea" },
	{ rank: 77, city: "Marrakesh", country: "Morocco" },
	{ rank: 78, city: "Chicago", country: "USA" },
	{ rank: 79, city: "Dublin", country: "Ireland" },
	{ rank: 80, city: "Toronto", country: "Canada" },
	{ rank: 81, city: "Brussels", country: "Belgium" },
	{ rank: 82, city: "Kuala Lumpur", country: "Malaysia" },
	{ rank: 83, city: "Jakarta", country: "Indonesia" },
	{ rank: 84, city: "Auckland", country: "New Zealand" },
	{ rank: 85, city: "Stockholm", country: "Sweden" },
	{ rank: 86, city: "Warsaw", country: "Poland" },
	{ rank: 87, city: "Beirut", country: "Lebanon" },
	{ rank: 88, city: "Vienna", country: "Austria" },
	{ rank: 89, city: "Dubai", country: "United Arab Emirates" },
	{ rank: 90, city: "Mumbai", country: "India" },
	{ rank: 91, city: "Singapore", country: "Singapore" },
	{ rank: 92, city: "Buenos Aires", country: "Argentina" },
	{ rank: 93, city: "Barcelona", country: "Spain" },
	{ rank: 94, city: "Saint Petersburg", country: "Russia" },
	{ rank: 95, city: "Amsterdam", country: "Netherlands" },
	{ rank: 96, city: "Nairobi", country: "Kenya" },
	{ rank: 97, city: "Copenhagen", country: "Denmark" },
	{ rank: 98, city: "Johannesburg", country: "South Africa" },
	{ rank: 99, city: "Sao Paulo", country: "Brazil" },
	{ rank: 100, city: "Bangalore", country: "India" },
];

export const CitiesList: ICitiesList[] = [
	{ Key: "28143", LocalizedName: "Dhaka", EnglishName: "Dhaka" },
	{ Key: "113487", LocalizedName: "Kinshasa", EnglishName: "Kinshasa" },
	{ Key: "60449", LocalizedName: "Santiago", EnglishName: "Santiago" },
	{ Key: "101924", LocalizedName: "Beijing", EnglishName: "Beijing" },
	{ Key: "107487", LocalizedName: "Bogota", EnglishName: "Bogota" },
	{ Key: "178087", LocalizedName: "Berlin", EnglishName: "Berlin" },
	{ Key: "127164", LocalizedName: "Cairo", EnglishName: "Cairo" },
	{ Key: "308526", LocalizedName: "Madrid", EnglishName: "Madrid" },
	{ Key: "328328", LocalizedName: "London", EnglishName: "London" },
	{ Key: "182536", LocalizedName: "Athens", EnglishName: "Athens" },
	{ Key: "1123655", LocalizedName: "Hong Kong", EnglishName: "Hong Kong" },
	{ Key: "208971", LocalizedName: "Jakarta", EnglishName: "Jakarta" },
	{ Key: "207375", LocalizedName: "Baghdad", EnglishName: "Baghdad" },
	{ Key: "226396", LocalizedName: "Tokyo", EnglishName: "Tokyo" },
	{ Key: "225058", LocalizedName: "Pyongyang", EnglishName: "Pyongyang" },
	{ Key: "226081", LocalizedName: "Seoul", EnglishName: "Seoul" },
	{ Key: "242560", LocalizedName: "Mexico City", EnglishName: "Mexico City" },
	{ Key: "264120", LocalizedName: "Lima", EnglishName: "Lima" },
	{ Key: "294021", LocalizedName: "Moscow", EnglishName: "Moscow" },
	{ Key: "297030", LocalizedName: "Riyadh", EnglishName: "Riyadh" },
	{ Key: "300597", LocalizedName: "Singapore", EnglishName: "Singapore" },
	{ Key: "318849", LocalizedName: "Bangkok", EnglishName: "Bangkok" },
	{ Key: "353412", LocalizedName: "Hanoi", EnglishName: "Hanoi" },
	{ Key: "22889", LocalizedName: "Sydney", EnglishName: "Sydney" },
	{ Key: "26216", LocalizedName: "Melbourne", EnglishName: "Melbourne" },
	{ Key: "45449", LocalizedName: "Rio de Janeiro", EnglishName: "Rio de Janeiro" },
	{ Key: "106577", LocalizedName: "Shanghai", EnglishName: "Shanghai" },
	{ Key: "202396", LocalizedName: "Delhi", EnglishName: "Delhi" },
	{ Key: "204108", LocalizedName: "Bengaluru", EnglishName: "Bengaluru" },
	{ Key: "204842", LocalizedName: "Mumbai", EnglishName: "Mumbai" },
	{ Key: "206671", LocalizedName: "Chennai", EnglishName: "Chennai" },
	{ Key: "206690", LocalizedName: "Kolkata", EnglishName: "Kolkata" },
	{ Key: "222888", LocalizedName: "Busan", EnglishName: "Busan" },
	{ Key: "246562", LocalizedName: "Yangon", EnglishName: "Yangon" },
	{ Key: "261158", LocalizedName: "Karachi", EnglishName: "Karachi" },
	{ Key: "295212", LocalizedName: "Saint Petersburg", EnglishName: "Saint Petersburg" },
	{ Key: "318251", LocalizedName: "Istanbul", EnglishName: "Istanbul" },
	{ Key: "353981", LocalizedName: "Ho Chi Minh City", EnglishName: "Ho Chi Minh City" },
	{ Key: "305448", LocalizedName: "Johannesburg", EnglishName: "Johannesburg" },
	{ Key: "4607", LocalizedName: "Lagos", EnglishName: "Lagos" },
	{ Key: "347625", LocalizedName: "Los Angeles", EnglishName: "Los Angeles" },
	{ Key: "349727", LocalizedName: "New York", EnglishName: "New York" },
	{ Key: "4361", LocalizedName: "Kabul", EnglishName: "Kabul" },
	{ Key: "16890", LocalizedName: "Yerevan", EnglishName: "Yerevan" },
	{ Key: "4651", LocalizedName: "Luanda", EnglishName: "Luanda" },
	{ Key: "7894", LocalizedName: "Buenos Aires", EnglishName: "Buenos Aires" },
	{ Key: "31868", LocalizedName: "Vienna", EnglishName: "Vienna" },
	{ Key: "51097", LocalizedName: "Sofia", EnglishName: "Sofia" },
	{ Key: "43348", LocalizedName: "Brasília", EnglishName: "Brasília" },
	{ Key: "28580", LocalizedName: "Minsk", EnglishName: "Minsk" },
	{ Key: "55487", LocalizedName: "Ottawa", EnglishName: "Ottawa" },
	{ Key: "122438", LocalizedName: "Havana", EnglishName: "Havana" },
	{ Key: "125594", LocalizedName: "Prague", EnglishName: "Prague" },
	{ Key: "125887", LocalizedName: "Santo Domingo", EnglishName: "Santo Domingo" },
	{ Key: "2093", LocalizedName: "Algiers", EnglishName: "Algiers" },
	{ Key: "129846", LocalizedName: "Quito", EnglishName: "Quito" },
	{ Key: "623", LocalizedName: "Paris", EnglishName: "Paris" },
	{ Key: "171705", LocalizedName: "Tbilisi", EnglishName: "Tbilisi" },
	{ Key: "189891", LocalizedName: "Port-au-prince", EnglishName: "Port-au-prince" },
	{ Key: "187423", LocalizedName: "Budapest", EnglishName: "Budapest" },
	{ Key: "210841", LocalizedName: "Tehran", EnglishName: "Tehran" },
	{ Key: "213490", LocalizedName: "Rome", EnglishName: "Rome" },
	{ Key: "224758", LocalizedName: "Nairobi", EnglishName: "Nairobi" },
	{ Key: "49785", LocalizedName: "Phnom Penh", EnglishName: "Phnom Penh" },
	{ Key: "222343", LocalizedName: "Astana", EnglishName: "Astana" },
	{ Key: "245072", LocalizedName: "Rabat", EnglishName: "Rabat" },
	{ Key: "246421", LocalizedName: "Ulan Bator", EnglishName: "Ulan Bator" },
	{ Key: "233776", LocalizedName: "Kuala Lumpur", EnglishName: "Kuala Lumpur" },
	{ Key: "264885", LocalizedName: "Manila", EnglishName: "Manila" },
	{ Key: "274663", LocalizedName: "Warsaw", EnglishName: "Warsaw" },
	{ Key: "287430", LocalizedName: "Bucharest", EnglishName: "Bucharest" },
	{ Key: "298198", LocalizedName: "Belgrade", EnglishName: "Belgrade" },
	{ Key: "308406", LocalizedName: "Khartoum", EnglishName: "Khartoum" },
	{ Key: "297442", LocalizedName: "Dakar", EnglishName: "Dakar" },
	{ Key: "297120", LocalizedName: "Mogadishu", EnglishName: "Mogadishu" },
	{ Key: "315078", LocalizedName: "Taipei City", EnglishName: "Taipei City" },
	{ Key: "324505", LocalizedName: "Kyiv", EnglishName: "Kyiv" },
	{ Key: "349269", LocalizedName: "Montevideo", EnglishName: "Montevideo" },
	{ Key: "351199", LocalizedName: "Tashkent", EnglishName: "Tashkent" },
	{ Key: "353020", LocalizedName: "Caracas", EnglishName: "Caracas" },
	{ Key: "355809", LocalizedName: "Sana'a", EnglishName: "Sana'a" },
	{ Key: "306633", LocalizedName: "Cape Town", EnglishName: "Cape Town" },
	{ Key: "353558", LocalizedName: "Harare", EnglishName: "Harare" },
	{ Key: "26797", LocalizedName: "Vienna", EnglishName: "Vienna" },
	{ Key: "31466", LocalizedName: "Baku", EnglishName: "Baku" },
	{ Key: "30023", LocalizedName: "Brussels", EnglishName: "Brussels" },
	{ Key: "31275", LocalizedName: "Sofia", EnglishName: "Sofia" },
	{ Key: "32355", LocalizedName: "Zagreb", EnglishName: "Zagreb" },
	{ Key: "31868", LocalizedName: "Vienna", EnglishName: "Vienna" },
	{ Key: "30720", LocalizedName: "Nicosia", EnglishName: "Nicosia" },
	{ Key: "125594", LocalizedName: "Prague", EnglishName: "Prague" },
	{ Key: "202966", LocalizedName: "Tallinn", EnglishName: "Tallinn" },
	{ Key: "31078", LocalizedName: "Helsinki", EnglishName: "Helsinki" },
	{ Key: "623", LocalizedName: "Paris", EnglishName: "Paris" },
	{ Key: "66125", LocalizedName: "Berlin", EnglishName: "Berlin" },
	{ Key: "187423", LocalizedName: "Budapest", EnglishName: "Budapest" },
	{ Key: "171705", LocalizedName: "Tbilisi", EnglishName: "Tbilisi" },
	{ Key: "183684", LocalizedName: "Athens", EnglishName: "Athens" },
	{ Key: "212869", LocalizedName: "Reykjavik", EnglishName: "Reykjavik" },
	{ Key: "213490", LocalizedName: "Rome", EnglishName: "Rome" },
	{ Key: "219138", LocalizedName: "Pristina", EnglishName: "Pristina" },
	{ Key: "214046", LocalizedName: "Riga", EnglishName: "Riga" },
	{ Key: "222025", LocalizedName: "Vilnius", EnglishName: "Vilnius" },
	{ Key: "233064", LocalizedName: "Luxembourg", EnglishName: "Luxembourg" },
	{ Key: "241084", LocalizedName: "Valletta", EnglishName: "Valletta" },
	{ Key: "264371", LocalizedName: "Amsterdam", EnglishName: "Amsterdam" },
	{ Key: "288620", LocalizedName: "Skopje", EnglishName: "Skopje" },
	{ Key: "274663", LocalizedName: "Warsaw", EnglishName: "Warsaw" },
	{ Key: "287430", LocalizedName: "Bucharest", EnglishName: "Bucharest" },
	{ Key: "298198", LocalizedName: "Belgrade", EnglishName: "Belgrade" },
	{ Key: "300098", LocalizedName: "Bratislava", EnglishName: "Bratislava" },
	{ Key: "306560", LocalizedName: "Ljubljana", EnglishName: "Ljubljana" },
	{ Key: "314929", LocalizedName: "Madrid", EnglishName: "Madrid" },
	{ Key: "317698", LocalizedName: "Stockholm", EnglishName: "Stockholm" },
	{ Key: "323786", LocalizedName: "Bern", EnglishName: "Bern" },
	{ Key: "324505", LocalizedName: "Kyiv", EnglishName: "Kyiv" },
	{ Key: "55449", LocalizedName: "Ottawa", EnglishName: "Ottawa" },
	{ Key: "57587", LocalizedName: "Mexico City", EnglishName: "Mexico City" },
	{ Key: "37573", LocalizedName: "Washington D.C.", EnglishName: "Washington D.C." },
];
